{{- $np := index .Values "kubetail" "agent" "networkPolicy" -}}
{{- if $np.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "kubetail.agent.networkPolicyName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.agent.labels" . | nindent 4 }}
    {{- with $np.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $np.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubetail.agent.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "kubetail.server.selectorLabels" . | nindent 10 }}
{{- end }}
