{{- $svc := index .Values "kubetail" "server" "service" -}}
{{- if $svc.create }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "kubetail.server.serviceName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.server.labels" . | nindent 4 }}
    {{- with $svc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $svc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubetail.server.selectorLabels" . | nindent 4 }}
  ports:
  {{- with $svc.ports }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
