{{- if .Values.kubetail.clusterAgent.enabled }}
{{- $bundle := include "kubetail.tlsBundle" $ | fromYaml }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "kubetail.clusterAgent.tlsSecretName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.clusterAgent.labels" (list $ dict) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ dict) | indent 4 }}
type: Opaque
data:
  ca.crt: {{ $bundle.caCert | b64enc }}
  tls.crt: {{ $bundle.agentCert | b64enc }}
  tls.key: {{ $bundle.agentKey | b64enc }}
{{- end }}
