namespaceOverride: kubetail-system

kubetail:
  secrets:
    KUBETAIL_DASHBOARD_SESSION_SIGNING_KEY1: "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMA=="
    KUBETAIL_DASHBOARD_SESSION_ENCRYPTION_KEY1: "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMA=="

  dashboard:
    authMode: token
