{{- $secret := index .Values "kubetail" "server" "secret" -}}
{{- if $secret.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "kubetail.server.secretName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.server.labels" (list $ $secret.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $secret.annotations) | indent 4 }}
type: Opaque
data:
  {{- $currentValsRef := dict "data" dict }}
  {{- $currentResource := (lookup "v1" "Secret" (include "kubetail.namespace" .) (include "kubetail.server.secretName" .)) }}
  {{- if $currentResource }}
  {{- $_ := set $currentValsRef "data" (index $currentResource "data") }}
  {{- end }}
  KUBETAIL_SERVER_CSRF_SECRET: {{ .Values.kubetail.secrets.KUBETAIL_SERVER_CSRF_SECRET | default $currentValsRef.data.KUBETAIL_SERVER_CSRF_SECRET | default ((randAlphaNum 32) | b64enc | quote) }}
  KUBETAIL_SERVER_SESSION_SECRET: {{ .Values.kubetail.secrets.KUBETAIL_SERVER_SESSION_SECRET | default $currentValsRef.data.KUBETAIL_SERVER_SESSION_SECRET | default ((randAlphaNum 32) | b64enc | quote) }}
{{- end }}
