{{- $secret := index .Values "kubetail" "server" "secret" -}}
{{- if $secret.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "kubetail.server.secretName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.server.labels" (list $ $secret.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $secret.annotations) | indent 4 }}
type: Opaque
data:
  {{- include "kubetail.server.secretData" . | nindent 2 }}
{{- end }}
