{{- $svc := index .Values "kubetail" "server" "service" -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "kubetail.server.serviceName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.server.labels" (list $ $svc.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $svc.annotations) | indent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubetail.server.selectorLabels" . | nindent 4 }}
  ports:
  - name: kubetail-server
    protocol: TCP
    port: {{ $svc.port }}
    targetPort: kubetail-server
    appProtocol: http
