{{- $r := index .Values "kubetail" "server" "role" -}}
{{- $rb := index .Values "kubetail" "server" "roleBinding" }}
{{- if eq .Values.kubetail.authMode "cluster" }}
{{- $cr := index .Values "kubetail" "server" "clusterRole" -}}
{{- $crb := index .Values "kubetail" "server" "clusterRoleBinding" -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubetail.server.clusterRoleName" . }}
  labels:
    {{- include "kubetail.server.labels" . | nindent 4 }}
    {{- with $cr.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $cr.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{- if .Values.kubetail.allowedNamespaces }}
- apiGroups: [""]
  resources: [namespaces, nodes]
  verbs: [get, list, watch]
{{- else }}
- apiGroups: ["", apps, batch]
  resources: [cronjobs, daemonsets, deployments, jobs, namespaces, nodes, pods, pods/log, replicasets, statefulsets]
  verbs: [get, list, watch]
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubetail.server.clusterRoleBindingName" . }}
  labels:
    {{- include "kubetail.server.labels" . | nindent 4 }}
    {{- with $crb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $crb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubetail.server.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubetail.server.serviceAccountName" . }}
  namespace: {{ include "kubetail.namespace" . }}
{{- range .Values.kubetail.allowedNamespaces }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ . }}
  name: {{ include "kubetail.server.roleName" $ }}
  labels:
    {{- include "kubetail.server.labels" $ | nindent 4 }}
    {{- with $r.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $r.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["", apps, batch]
  resources: [cronjobs, daemonsets, deployments, jobs, pods, pods/log, replicasets, statefulsets]
  verbs: [get, list, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ . }}
  name: {{ include "kubetail.server.roleBindingName" $ }}
  labels:
    {{- include "kubetail.server.labels" $ | nindent 4 }}
    {{- with $rb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $rb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubetail.server.roleName" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubetail.server.serviceAccountName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
{{- end }}
{{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ include "kubetail.namespace" . }}
  name: {{ include "kubetail.server.roleName" $ }}-grpc
  labels:
    {{- include "kubetail.server.labels" $ | nindent 4 }}
    {{- with $r.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $r.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: [discovery.k8s.io]
  resources: [endpointslices]
  verbs: [list, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ include "kubetail.namespace" . }}
  name: {{ include "kubetail.server.roleBindingName" $ }}-grpc
  labels:
    {{- include "kubetail.server.labels" $ | nindent 4 }}
    {{- with $rb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $rb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubetail.server.roleName" $ }}-grpc
subjects:
- kind: ServiceAccount
  name: {{ include "kubetail.server.serviceAccountName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
