{{- if .Values.kubetail.api.enabled }}
{{- $dep := index .Values "kubetail" "api" "deployment" -}}
{{- $podTmpl := index .Values "kubetail" "api" "podTemplate" }}
{{- $container := index .Values "kubetail" "api" "container" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "kubetail.api.deploymentName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.api.labels" (list $ $dep.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $dep.annotations) | indent 4 }}
spec:
  replicas: {{ $dep.replicas }}
  revisionHistoryLimit: {{ $dep.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "kubetail.api.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml $dep.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "kubetail.api.labels" (list $ $podTmpl.labels) | indent 8 }}
      annotations:
        {{- include "kubetail.annotations" (list $ $podTmpl.annotations) | indent 8 }}
        checksum/config: {{ include "kubetail.api.config" . | sha256sum | quote }}
    spec:
      automountServiceAccountToken: true
      {{- if eq .Values.kubetail.authMode "cluster" }}
      serviceAccountName: {{ include "kubetail.api.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- with $podTmpl.securityContext -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: {{ $container.name }}
        image: {{ include "kubetail.api.image" . }}
        securityContext:
          {{- with $container.securityContext -}}
          {{ toYaml . | nindent 10 }}
          {{- end }}
        imagePullPolicy: {{ .Values.kubetail.api.image.pullPolicy }}
        env:
        {{- with $container.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        {{- with $container.extraEnvFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
        - --config=/etc/kubetail/config.yaml
        ports:
        - name: grpc
          protocol: TCP
          containerPort: {{ .Values.kubetail.api.runtimeConfig.ports.grpc }}
        livenessProbe:
          grpc:
            port: {{ .Values.kubetail.api.runtimeConfig.ports.grpc }}
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: {{ .Values.kubetail.api.runtimeConfig.ports.grpc }}
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        resources:
          {{- with $container.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
      {{- with $podTmpl.extraContainers  }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "kubetail.api.configMapName" . }}
      nodeSelector:
        {{- with $podTmpl.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      affinity:
        {{- with $podTmpl.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      tolerations:
      {{- with $podTmpl.tolerations }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
{{- end }}
