name: ci

permissions:
  contents: read

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - name: Run linter
        run: |
          make lint
