name: release-post

on:
  push:
    tags:
      - 'kubetail-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create quickstart manifests
        run: |
          helm template kubetail charts/kubetail --values hack/kubetail-values-clusterauth.yaml > kubetail-clusterauth.yaml
          helm template kubetail charts/kubetail --values hack/kubetail-values-tokenauth.yaml > kubetail-tokenauth.yaml

      - name: Attach quickstart manifests to gh release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            kubetail-clusterauth.yaml
            kubetail-tokenauth.yaml
