{{- if .Values.kubetail.agent.enabled }}
{{- $cfgMap := index .Values "kubetail" "agent" "configMap" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kubetail.agent.configMapName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.agent.labels" (list $ $cfgMap.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $cfgMap.annotations) | indent 4 }}
data:
  config.yaml: |
    {{- include "kubetail.agent.config" . | nindent 4 }}
{{- end }}
