{{- if .Values.kubetail.agent.enabled }}
{{- $svc := index .Values "kubetail" "agent" "service" -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "kubetail.agent.serviceName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.agent.labels" (list $ $svc.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $svc.annotations) | indent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kubetail.agent.selectorLabels" . | nindent 4 }}
{{- end }}
